version: 0.0
os: linux

files:
  - source: /app_code/index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
  
hooks:
  BeforeInstall:
    - location: scripts/update_dependencies.sh
      timeout: 350
      runas: root

    - location: scripts/install_httpd.sh
      timeout: 350
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 350
      runas: root

  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 350
      runas: root
