name: 'Build resources and Deploy to AWS Codecommit'

on:
  push:
    branches: [ "master" ]


permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  codecommit_repo: zero-downtime-repo-name

jobs:
  build_resources:
    name: 'Build Resources'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Export Terraform TFVARS file
      working-directory: ./infrastructure
      run: |
        echo "$TERRAFORM_VARIABLES" >> terraform.tfvars
      shell: bash
      env:
        TERRAFORM_VARIABLES: ${{ secrets.TERRAFORM_VARIABLES }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_WEB_IDENTITY_ROLE_ARN }}
        aws-region: us-east-1

    - name: Terraform Init
      working-directory: ./infrastructure
      run: terraform init -upgrade

    - name: Terraform Format  
      working-directory: ./infrastructure
      run: terraform fmt -check

    - name: Terraform Plan
      working-directory: ./infrastructure
      run: terraform plan -lock=false -var-file="terraform.tfvars"

    - name: Terraform apply 
      working-directory: ./infrastructure
      run: terraform apply -lock=false -var-file="terraform.tfvars" --auto-approve
  
  push_to_codecommit:
    name: 'Push to Codecommit'
    runs-on: ubuntu-latest
    environment: production
    needs: build_resources

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.AWS_WEB_IDENTITY_ROLE_ARN }}
        aws-region: us-east-1

    - name: Sync up to CodeCommit
      uses: tsgit18/sync-up-to-codecommit-action@v1
      with:
        repository_name: ${{ env.codecommit_repo }}
        aws_region: us-east-1



